In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

train = pd.read_csv('Train.csv')
test = pd.read_csv('Test.csv')
variables = pd.read_csv('VariableDefinitions.csv', encoding="cp1252")
sample = pd.read_csv('SampleSubmission.csv')


print(train.shape)
print(test.shape)
print(variables.shape)
print(sample.shape)

(23524, 13)
(10086, 12)
(12, 2)
(33610, 2)

In [4]:
variables

      Variable Definitions                                         Unnamed: 1
0                  country                         Country interviewee is in.
1                     year                           Year survey was done in.
2                 uniqueid             Unique identifier for each interviewee
3            location_type                     Type of location: Rural, Urban
4         cellphone_access  If interviewee has access to a cellphone: Yes, No
5           household_size               Number of people living in one house
6        age_of_respondent                         The age of the interviewee
7     gender_of_respondent                Gender of interviewee: Male, Female
8   relationship_with_head  The interviewee’s relationship with the head o...
9           marital_status  The martial status of the interviewee: Married...
10         education_level  Highest level of education: No formal educatio...
11                job_type  Type of job interviewee has: Farming and Fishi...

In [5]:
train.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [6]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  str
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  str
 3   bank_account            23524 non-null  str
 4   location_type           23524 non-null  str
 5   cellphone_access        23524 non-null  str
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  str
 9   relationship_with_head  23524 non-null  str
 10  marital_status          23524 non-null  str
 11  education_level         23524 non-null  str
 12  job_type                23524 non-null  str
dtypes: int64(3), str(10)
memory usage: 2.3 MB

In [7]:
train.describe()

               year  household_size  age_of_respondent
count  23524.000000    23524.000000       23524.000000
mean    2016.975939        3.797483          38.805220
std        0.847371        2.227613          16.520569
min     2016.000000        1.000000          16.000000
25%     2016.000000        2.000000          26.000000
50%     2017.000000        3.000000          35.000000
75%     2018.000000        5.000000          49.000000
max     2018.000000       21.000000         100.000000

In [8]:
train['country'].value_counts()

country
Rwanda      8735
Tanzania    6620
Kenya       6068
Uganda      2101
Name: count, dtype: int64

In [9]:
train['bank_account'].value_counts()

bank_account
No     20212
Yes     3312
Name: count, dtype: int64

In [10]:
pd.crosstab(
    train['country'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account         No        Yes
country
Kenya         74.934080  25.065920
Rwanda        88.517459  11.482541
Tanzania      90.830816   9.169184
Uganda        91.385055   8.614945

In [11]:
pd.crosstab(
    train['education_level'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account                            No        Yes
education_level
No formal education              96.101883   3.898117
Other/Dont know/RTA              68.571429  31.428571
Primary education                91.454929   8.545071
Secondary education              76.722709  23.277291
Tertiary education               48.919620  51.080380
Vocational/Specialised training  42.963885  57.036115

In [12]:
train['education_level'].value_counts()

education_level
Primary education                  12791
No formal education                 4515
Secondary education                 4223
Tertiary education                  1157
Vocational/Specialised training      803
Other/Dont know/RTA                   35
Name: count, dtype: int64

In [13]:
train['job_type'].value_counts()

job_type
Self employed                   6437
Informally employed             5597
Farming and Fishing             5441
Remittance Dependent            2527
Other Income                    1080
Formally employed Private       1055
No Income                        627
Formally employed Government     387
Government Dependent             247
Dont Know/Refuse to answer       126
Name: count, dtype: int64

In [14]:
pd.crosstab(
    train['job_type'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account                         No        Yes
job_type
Dont Know/Refuse to answer    88.888889  11.111111
Farming and Fishing           88.329351  11.670649
Formally employed Government  22.480620  77.519380
Formally employed Private     45.876777  54.123223
Government Dependent          79.757085  20.242915
Informally employed           92.049312   7.950688
No Income                     97.926635   2.073365
Other Income                  81.851852  18.148148
Remittance Dependent          90.502572   9.497428
Self employed                 86.826161  13.173839

In [15]:
train['cellphone_access'].value_counts()

cellphone_access
Yes    17454
No      6070
Name: count, dtype: int64

In [16]:
pd.crosstab(
    train['cellphone_access'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account             No        Yes
cellphone_access
No                98.286656   1.713344
Yes               81.620259  18.379741

In [17]:
train['location_type'].value_counts()

location_type
Rural    14343
Urban     9181
Name: count, dtype: int64

In [18]:
pd.crosstab(
    train['location_type'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account          No        Yes
location_type
Rural          88.349718  11.650282
Urban          82.126130  17.873870

In [19]:
train['gender_of_respondent'].value_counts()

gender_of_respondent
Female    13877
Male       9647
Name: count, dtype: int64

In [20]:
train['relationship_with_head'].value_counts()

relationship_with_head
Head of Household      12831
Spouse                  6520
Child                   2229
Parent                  1086
Other relative           668
Other non-relatives      190
Name: count, dtype: int64

In [21]:
train['marital_status'].value_counts()

marital_status
Married/Living together    10749
Single/Never Married        7983
Widowed                     2708
Divorced/Seperated          2076
Dont know                      8
Name: count, dtype: int64

In [24]:
train['household_size'].value_counts().sort_index()

household_size
1     3057
2     5229
3     3920
4     3474
5     2853
6     2096
7     1400
8      751
9      363
10     190
11      69
12      68
13      25
14      10
15      11
16       4
17       1
18       1
20       1
21       1
Name: count, dtype: int64

In [23]:
train['age_of_respondent'].describe()

count    23524.000000
mean        38.805220
std         16.520569
min         16.000000
25%         26.000000
50%         35.000000
75%         49.000000
max        100.000000
Name: age_of_respondent, dtype: float64

In [25]:
train['year'].value_counts().sort_index()

year
2016    8735
2017    6620
2018    8169
Name: count, dtype: int64

In [26]:
categorical_cols = [
    'gender_of_respondent',
    'relationship_with_head',
    'marital_status'
]

for col in categorical_cols:
    print(f"\n{'='*50}")
    print(col)
    print(pd.crosstab(
        train[col],
        train['bank_account'],
        normalize='index'
    ) * 100)

==================================================
gender_of_respondent
bank_account                 No        Yes
gender_of_respondent
Female                89.320458  10.679542
Male                  81.030372  18.969628

==================================================
relationship_with_head
bank_account                   No        Yes
relationship_with_head
Child                   91.341409   8.658591
Head of Household       82.285091  17.714909
Other non-relatives     89.473684  10.526316
Other relative          90.119760   9.880240
Parent                  94.014733   5.985267
Spouse                  89.340491  10.659509

==================================================
marital_status
bank_account                    No        Yes
marital_status
Divorced/Seperated       88.728324  11.271676
Dont know                75.000000  25.000000
Married/Living together  82.640246  17.359754
Single/Never Married     87.899286  12.100714
Widowed                  90.989660   9.010340

In [27]:
train.groupby('bank_account')[[
    'household_size',
    'age_of_respondent',
    'year'
]].describe()

             household_size                                                \
                      count      mean       std  min  25%  50%  75%   max
bank_account
No                  20212.0  3.823026  2.234618  1.0  2.0  3.0  5.0  21.0
Yes                  3312.0  3.641606  2.178225  1.0  2.0  3.0  5.0  17.0

             age_of_respondent             ...                  year  \
                         count       mean  ...   75%    max    count
bank_account                               ...
No                     20212.0  38.675292  ...  49.0  100.0  20212.0
Yes                     3312.0  39.598128  ...  48.0   95.0   3312.0


                     mean       std     min     25%     50%     75%     max
bank_account
No            2016.937413  0.835835  2016.0  2016.0  2017.0  2018.0  2018.0
Yes           2017.211051  0.878873  2016.0  2016.0  2018.0  2018.0  2018.0

[2 rows x 24 columns]