In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
     ---------------------------------------- 9.9/9.9 MB 505.5 kB/s eta 0:00:00
Collecting numpy>=1.26.0
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
     -------------------------------------- 12.6/12.6 MB 299.6 kB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata
  Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
     ------------------------------------ 347.5/347.5 kB 744.5 kB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.6 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

train = pd.read_csv('Train.csv')
test = pd.read_csv('Test.csv')
variables = pd.read_csv('VariableDefinitions.csv', encoding="cp1252")
sample = pd.read_csv('SampleSubmission.csv')


print(train.shape)
print(test.shape)
print(variables.shape)
print(sample.shape)

(23524, 13)
(10086, 12)
(12, 2)
(33610, 2)

In [3]:
variables

      Variable Definitions                                         Unnamed: 1
0                  country                         Country interviewee is in.
1                     year                           Year survey was done in.
2                 uniqueid             Unique identifier for each interviewee
3            location_type                     Type of location: Rural, Urban
4         cellphone_access  If interviewee has access to a cellphone: Yes, No
5           household_size               Number of people living in one house
6        age_of_respondent                         The age of the interviewee
7     gender_of_respondent                Gender of interviewee: Male, Female
8   relationship_with_head  The interviewee’s relationship with the head o...
9           marital_status  The martial status of the interviewee: Married...
10         education_level  Highest level of education: No formal educatio...
11                job_type  Type of job interviewee has: Farming and Fishi...

In [4]:
train.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  str
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  str
 3   bank_account            23524 non-null  str
 4   location_type           23524 non-null  str
 5   cellphone_access        23524 non-null  str
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  str
 9   relationship_with_head  23524 non-null  str
 10  marital_status          23524 non-null  str
 11  education_level         23524 non-null  str
 12  job_type                23524 non-null  str
dtypes: int64(3), str(10)
memory usage: 2.3 MB

In [6]:
train.describe()

               year  household_size  age_of_respondent
count  23524.000000    23524.000000       23524.000000
mean    2016.975939        3.797483          38.805220
std        0.847371        2.227613          16.520569
min     2016.000000        1.000000          16.000000
25%     2016.000000        2.000000          26.000000
50%     2017.000000        3.000000          35.000000
75%     2018.000000        5.000000          49.000000
max     2018.000000       21.000000         100.000000

In [7]:
train['country'].value_counts()

country
Rwanda      8735
Tanzania    6620
Kenya       6068
Uganda      2101
Name: count, dtype: int64

In [8]:
train['bank_account'].value_counts()

bank_account
No     20212
Yes     3312
Name: count, dtype: int64

In [9]:
pd.crosstab(
    train['country'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account         No        Yes
country
Kenya         74.934080  25.065920
Rwanda        88.517459  11.482541
Tanzania      90.830816   9.169184
Uganda        91.385055   8.614945

In [10]:
pd.crosstab(
    train['education_level'],
    train['bank_account'],
    normalize='index'
) * 100

bank_account                            No        Yes
education_level
No formal education              96.101883   3.898117
Other/Dont know/RTA              68.571429  31.428571
Primary education                91.454929   8.545071
Secondary education              76.722709  23.277291
Tertiary education               48.919620  51.080380
Vocational/Specialised training  42.963885  57.036115

In [11]:
train['education_level'].value_counts()

education_level
Primary education                  12791
No formal education                 4515
Secondary education                 4223
Tertiary education                  1157
Vocational/Specialised training      803
Other/Dont know/RTA                   35
Name: count, dtype: int64